version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gem_marketplace_app
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://13.60.10.35
      - APP_KEY=base64:PkDrrjQqzjXuYg6DUpbn1Yjm/QbNPH/OnJb4HBjj8fU=
      - DB_CONNECTION=mysql
      - DB_HOST=shyamgems.c7c4w8eokqa2.eu-north-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_DATABASE=my_gem_platform
      - DB_USERNAME=admin # Replace with your RDS username
      - DB_PASSWORD=secure_password # Replace with your RDS password
      - MONGO_DB_CONNECTION=mongodb
      - MONGO_DB_HOST=mongodb+srv://<atlas-username>:<atlas-password>@cluster0.mongodb.net
      - MONGO_DB_PORT=27017
      - MONGO_DB_DATABASE=my_gem_platform_mongo
      - MONGO_DB_USERNAME= # Optional, included in connection string
      - MONGO_DB_PASSWORD= # Optional, included in connection string
      - REVERB_HOST=gem_marketplace_reverb
      - REVERB_PORT=8080
      - VITE_REVERB_HOST=13.60.10.35
      - VITE_REVERB_PORT=8080
    networks:
      - gem-marketplace-network

  nginx:
    image: nginx:alpine
    container_name: gem_marketplace_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - gem-marketplace-network

  reverb:
    image: beyondcode/laravel-websockets
    container_name: gem_marketplace_reverb
    ports:
      - "8080:8080"
    environment:
      - LARAVEL_WEBSOCKETS_PORT=8080
      - LARAVEL_WEBSOCKETS_HOST=0.0.0.0
    volumes:
      - .:/var/www
    depends_on:
      - app
    networks:
      - gem-marketplace-network

networks:
  gem-marketplace-network:
    driver: bridge